In [1]:
import json
import pandas as pd
import re

with open('games.json', encoding="utf8") as file:
    d=json.loads(file.read())

new_games_df = pd.DataFrame.from_dict(d).T.drop(['affiliate_links', 'backloggd_link', 'content', 'submitted_by', 'twitter_ids'], axis=1)
new_games_df["game"] = new_games_df['answers'].apply(lambda x: x[0])
new_games_df = new_games_df.drop(['answers'], axis=1)

def clear_platforms(x):
    x = re.sub(r'\(.*\)', '', x)
    if x.startswith('2020: PC'):
        return ['PC']
    x = x.replace(".", ",")
    x = x.split(",")
    x = [s.strip() for s in x]
    x = ["PS1" if s == "PS" else s for s in x]
    x = ["X360" if s == "360" else s for s in x]
    x = ["GameCube" if s == "Gamecube" else s for s in x]
    x = ["Xbox Series" if s == "X Series X/S" else s for s in x]
    x = ["Xbox Series" if s == "Series X/S" else s for s in x]
    x = ["Xbox Series" if s == "Xbox series" else s for s in x]
    x = ["Mac" if s == "Macintosh" else s for s in x]
    return x

new_games_df["console_platform"] = new_games_df["console_platform"].apply(clear_platforms)

def clear_genres(x):
    x = re.sub(r'\(.*\)', '', x)
    x = x.replace(".", ",")
    x = x.split(",")
    x = [s.strip().casefold() for s in x]
    return x

new_games_df["genre"] = new_games_df["genre"].apply(clear_genres)

def clear_metacritic(x):
    if x and x[0].isalpha():
        return None
    x = re.search(r"[0-9]+", x)
    return x.group(0)

new_games_df["metacritic_score"] = new_games_df["metacritic_score"].apply(clear_metacritic)
new_games_df["metacritic_score"] = new_games_df["metacritic_score"].astype(float)

new_games_df["release_year"] = new_games_df["release_year"].apply(lambda x: re.search(r"[0-9]{4}", x).group(0))
new_games_df["release_year"] = new_games_df["release_year"].astype(int)

new_games_df["day"] = new_games_df.index.astype(int)

new_games_df.head(10)

,console_platform,developer,franchise,genre,metacritic_score,release_year,game,day
1,"[PC, PS3, X360]",Bioware,Mass Effect,"[action, rpg]",89.0,2012,Mass Effect 3,1
2,[N64],Nintendo,The Legend of Zelda,"[action, adventure]",99.0,1998,The Legend of Zelda: Ocarina of Time,2
3,"[PC, PS4, XONE, Switch]",Mobius Digital,None,"[open world, puzzle]",85.0,2019,Outer Wilds,3
4,[PS4],Guerrilla Games,Horizon,"[action, rpg]",89.0,2017,Horizon Zero Dawn,4
5,[PC],LucasArts,Monkey Island,"[point & click, adventure]",NaN,1990,The Secret of Monkey Island,5
6,[PS2],Rockstar Games,Grand Theft Auto,"[action, adventure]",93.0,2001,Grand Theft Auto 3,6
7,[GameCube],Capcom Production Studio 4,Resident Evil,"[survival, horror, action, adventure]",96.0,2005,Resident Evil 4,7
8,"[PC, PS3, X360]",Valve,Portal,[puzzle],95.0,2011,Portal 2,8
9,[PS2],SCE Japan Studio,Ico,"[action, adventure]",91.0,2005,Shadow of the Colossus,9
10,[N64],Nintendo,Mario,[sports],91.0,1999,Mario Golf,10

In [ ]:
len()

In [5]:
new_games_df[new_games_df['console_platform'].apply(lambda x: 'Genesis' in x or 'Dreamcast' in x)]

,console_platform,developer,franchise,genre,metacritic_score,release_year,game,day
177,[Genesis],Sonic Team,Sonic The Hedgehog,[platformer],NaN,1991,Sonic the Hedgehog,177
347,[Dreamcast],Sonic Team USA,Sonic The Hedgehog,"[platform, action, adventure]",89.0,2001,Sonic Adventure 2,347
418,[Dreamcast],Smilebit,Jet Set Radio,[action],94.0,2000,Jet Set Radio,418
502,[Dreamcast],Sonic Team,Sonic The Hedgehog,[action],NaN,1999,Sonic Adventure,502
524,"[PS1, PC, Dreamcast]","Neversoft Entertainment, Inc.",Tony Hawk,[sports],91.0,2000,Tony Hawk's Pro Skater 2,524
706,"[DOS, SNES, Amiga, Genesis]","Silicon & Synapse, Inc.",The Lost Vikings,"[puzzle, platformer]",NaN,1993,The Lost Vikings,706
824,"[PC, PS1, Dreamcast]",Core Design,Tomb Raider,"[action, adventure, platform]",NaN,1999,Tomb Raider: The Last Revelation,824
859,[Dreamcast],Overworks,Skies of Arcadia,"[jrpg, adventure]",93.0,2000,Skies of Arcadia,859
876,"[Arcade, Dreamcast, PS2]",Team Ninja,Dead or Alive,[fighting],NaN,1999,Dead or Alive 2,876
894,[Genesis],Sega Technical Institute,Sonic The Hedgehog,[platformer],NaN,1992,Sonic the Hedgehog 2,894
900,"[SNES, Genesis]","Shiny Entertainment, Inc.",Earthworm Jim,"[platformer, adventure]",NaN,1994,Earthworm Jim,900

In [14]:
import numpy as np

values = []
for row in new_games_df["genre"].tail(200):
    values.append(row)
unique, counts = np.unique(np.concatenate(values), return_counts=True)
pd.DataFrame({'val': unique, 'count': counts}).sort_values(by='count', ascending=False).head(50)

                     val  count
4                 action     71
6              adventure     48
55                   rpg     27
22                   fps     22
42              platform     19
71              survival     16
2             3rd person     15
26                horror     15
62               shooter     11
76            turn based      9
49       puzzle elements      9
25          hack & slash      9
67                sports      9
68               stealth      9
19               fantasy      8
48                puzzle      8
56          rpg elements      7
8                 arcade      7
70              strategy      6
57                   rts      6
54          role playing      5
53             roguelike      5
43            platformer      5
74  third person shooter      5
64            simulation      4
33          metroidvania      4
38            open world      4
50       puzzle platform      3
29                  jrpg      3
75              top down      3
46      post apocalyptic      3
63             side view      3
35                mmorpg      3
5    action role playing      2
10           beat 'em up      2
21              fighting      2
12         city building      2
40            party game      2
72              tactical      2
1             1st person      2
34                   mmo      2
24     graphic adventure      2
59                sci fi      2
31       life simulation      2
11  cinematic platformer      1
61          shoot 'em up      1
60                sci-fi      1
27               horror?      1
69          storytelling      1
65            souls like      1

In [3]:
import numpy as np

values = []
for row in new_games_df["console_platform"]:
    values.append(row)
unique, counts = np.unique(np.concatenate(values), return_counts=True)
pd.DataFrame({'val': unique, 'count': counts}).sort_values(by='count', ascending=False)

               val  count
28              PC    565
35             PS4    186
46            XONE    150
45            X360    134
34             PS3    114
41          Switch     85
36             PS5     82
49     Xbox Series     79
33             PS2     63
23          Mobile     45
32             PS1     41
16        GameCube     40
48            Xbox     36
4           Arcade     30
9              DOS     25
43             Wii     19
24             N64     18
38            SNES     16
14             GBA     15
10              DS     15
44           Wii U     13
25             NES     13
21             Mac     10
47            XOne     10
37             PSP      9
0              3DS      9
1            Amiga      8
31         PS Vita      8
40          Stadia      8
11       Dreamcast      7
18           Linux      5
7          Browser      4
17         Genesis      4
42              VR      2
3         Apple II      2
6         Atari ST      2
15        Game Boy      2
8     Commodore 64      2
26       Odyssey 2      1
2      Amstrad CPC      1
5       Atari 2600      1
13        FM Towns      1
12  Electronika 60      1
39     Sega Saturn      1
27            Ouya      1
19            Luna      1
20            Lynx      1
22       Mainframe      1
30           PS VR      1
29         PC-6001      1
50     ZX Spectrum      1

In [10]:
import numpy as np

unique, counts = np.unique(new_games_df["developer"], return_counts=True)
pd.DataFrame({'val': unique, 'count': counts}).sort_values(by='count', ascending=False)[50:100]

                                     val  count
43                                 Atlus      3
347                  NetherRealm Studios      3
375               Obsidian Entertainment      3
351                     Next Level Games      3
264                         Japan Studio      3
338                        Namco Limited      3
286                Lionhead Studios Ltd.      3
396                  Platinum Games Inc.      3
388                     Pandemic Studios      3
349        Neversoft Entertainment, Inc.      3
343                    Naughty Dog, Inc.      3
304                       Media Molecule      3
293  LucasArts Entertainment Company LLC      3
348                            Neversoft      2
458               Rocksteady Studios Ltd      2
169         Ensemble Studios Corporation      2
175                    Facepunch Studios      2
397                        PlatinumGames      2
532                         Subset Games      2
146              Double Fine Productions      2
390           Paradox Development Studio      2
399                             Playdead      2
142                Dontnod Entertainment      2
353                  Night School Studio      2
554                          Team Silent      2
133                       Dennaton Games      2
558                             Techland      2
125                           DMA Design      2
566                       Terry Cavanagh      2
567                           Teyon S.A.      2
568                      Thatgamecompany      2
117                               Crytek      2
179                        Firaxis Games      2
323                 Monolith Productions      2
325                        Monolith Soft      2
324           Monolith Productions, Inc.      2
457                   Rocksteady Studios      2
455                     Rockstar Studios      2
271                   Klei Entertainment      2
115                     Crystal Dynamics      2
272                   Kojima Productions      2
471                 Sabotage Studio Inc.      2
276  Konami Computer Entertainment Japan      2
240                           ILCA, Inc.      2
475                  Santa Monica Studio      2
444                           Riot Games      2
278  Konami Computer Entertainment Tokyo      2
442                        Retro Studios      2
487            Shiny Entertainment, Inc.      2
282                       Larian Studios      2